# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mikhail/.local/share/JetBrains/apps/CLion/ch-0/163.9166.31/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/mikhail/.local/share/JetBrains/apps/CLion/ch-0/163.9166.31/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Data/Dropbox/Study/cs/3. CS MSU cs cources/3.1 Машграф/projects/mashgraph3"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Data/Dropbox/Study/cs/3. CS MSU cs cources/3.1 Машграф/projects/mashgraph3"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/mikhail/.local/share/JetBrains/apps/CLion/ch-0/163.9166.31/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mikhail/.local/share/JetBrains/apps/CLion/ch-0/163.9166.31/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Data/Dropbox/Study/cs/3. CS MSU cs cources/3.1 Машграф/projects/mashgraph3/CMakeFiles" "/Data/Dropbox/Study/cs/3. CS MSU cs cources/3.1 Машграф/projects/mashgraph3/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Data/Dropbox/Study/cs/3. CS MSU cs cources/3.1 Машграф/projects/mashgraph3/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named make

# Build rule for target.
make: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make
.PHONY : make

# fast build rule for target.
make/fast:
	$(MAKE) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/build
.PHONY : make/fast

#=============================================================================
# Target rules for targets named cmake_project

# Build rule for target.
cmake_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmake_project
.PHONY : cmake_project

# fast build rule for target.
cmake_project/fast:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/build
.PHONY : cmake_project/fast

#=============================================================================
# Target rules for targets named SOIL

# Build rule for target.
SOIL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SOIL
.PHONY : SOIL

# fast build rule for target.
SOIL/fast:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/build
.PHONY : SOIL/fast

SOIL/src/SOIL.o: SOIL/src/SOIL.c.o

.PHONY : SOIL/src/SOIL.o

# target to build an object file
SOIL/src/SOIL.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/SOIL.c.o
.PHONY : SOIL/src/SOIL.c.o

SOIL/src/SOIL.i: SOIL/src/SOIL.c.i

.PHONY : SOIL/src/SOIL.i

# target to preprocess a source file
SOIL/src/SOIL.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/SOIL.c.i
.PHONY : SOIL/src/SOIL.c.i

SOIL/src/SOIL.s: SOIL/src/SOIL.c.s

.PHONY : SOIL/src/SOIL.s

# target to generate assembly for a file
SOIL/src/SOIL.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/SOIL.c.s
.PHONY : SOIL/src/SOIL.c.s

SOIL/src/image_DXT.o: SOIL/src/image_DXT.c.o

.PHONY : SOIL/src/image_DXT.o

# target to build an object file
SOIL/src/image_DXT.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/image_DXT.c.o
.PHONY : SOIL/src/image_DXT.c.o

SOIL/src/image_DXT.i: SOIL/src/image_DXT.c.i

.PHONY : SOIL/src/image_DXT.i

# target to preprocess a source file
SOIL/src/image_DXT.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/image_DXT.c.i
.PHONY : SOIL/src/image_DXT.c.i

SOIL/src/image_DXT.s: SOIL/src/image_DXT.c.s

.PHONY : SOIL/src/image_DXT.s

# target to generate assembly for a file
SOIL/src/image_DXT.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/image_DXT.c.s
.PHONY : SOIL/src/image_DXT.c.s

SOIL/src/image_helper.o: SOIL/src/image_helper.c.o

.PHONY : SOIL/src/image_helper.o

# target to build an object file
SOIL/src/image_helper.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/image_helper.c.o
.PHONY : SOIL/src/image_helper.c.o

SOIL/src/image_helper.i: SOIL/src/image_helper.c.i

.PHONY : SOIL/src/image_helper.i

# target to preprocess a source file
SOIL/src/image_helper.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/image_helper.c.i
.PHONY : SOIL/src/image_helper.c.i

SOIL/src/image_helper.s: SOIL/src/image_helper.c.s

.PHONY : SOIL/src/image_helper.s

# target to generate assembly for a file
SOIL/src/image_helper.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/image_helper.c.s
.PHONY : SOIL/src/image_helper.c.s

SOIL/src/stb_image_aug.o: SOIL/src/stb_image_aug.c.o

.PHONY : SOIL/src/stb_image_aug.o

# target to build an object file
SOIL/src/stb_image_aug.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/stb_image_aug.c.o
.PHONY : SOIL/src/stb_image_aug.c.o

SOIL/src/stb_image_aug.i: SOIL/src/stb_image_aug.c.i

.PHONY : SOIL/src/stb_image_aug.i

# target to preprocess a source file
SOIL/src/stb_image_aug.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/stb_image_aug.c.i
.PHONY : SOIL/src/stb_image_aug.c.i

SOIL/src/stb_image_aug.s: SOIL/src/stb_image_aug.c.s

.PHONY : SOIL/src/stb_image_aug.s

# target to generate assembly for a file
SOIL/src/stb_image_aug.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/SOIL/src/stb_image_aug.c.s
.PHONY : SOIL/src/stb_image_aug.c.s

Utility/src/Camera.o: Utility/src/Camera.cpp.o

.PHONY : Utility/src/Camera.o

# target to build an object file
Utility/src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Camera.cpp.o
.PHONY : Utility/src/Camera.cpp.o

Utility/src/Camera.i: Utility/src/Camera.cpp.i

.PHONY : Utility/src/Camera.i

# target to preprocess a source file
Utility/src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Camera.cpp.i
.PHONY : Utility/src/Camera.cpp.i

Utility/src/Camera.s: Utility/src/Camera.cpp.s

.PHONY : Utility/src/Camera.s

# target to generate assembly for a file
Utility/src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Camera.cpp.s
.PHONY : Utility/src/Camera.cpp.s

Utility/src/GL.o: Utility/src/GL.cpp.o

.PHONY : Utility/src/GL.o

# target to build an object file
Utility/src/GL.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/GL.cpp.o
.PHONY : Utility/src/GL.cpp.o

Utility/src/GL.i: Utility/src/GL.cpp.i

.PHONY : Utility/src/GL.i

# target to preprocess a source file
Utility/src/GL.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/GL.cpp.i
.PHONY : Utility/src/GL.cpp.i

Utility/src/GL.s: Utility/src/GL.cpp.s

.PHONY : Utility/src/GL.s

# target to generate assembly for a file
Utility/src/GL.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/GL.cpp.s
.PHONY : Utility/src/GL.cpp.s

Utility/src/Overall.o: Utility/src/Overall.cpp.o

.PHONY : Utility/src/Overall.o

# target to build an object file
Utility/src/Overall.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Overall.cpp.o
.PHONY : Utility/src/Overall.cpp.o

Utility/src/Overall.i: Utility/src/Overall.cpp.i

.PHONY : Utility/src/Overall.i

# target to preprocess a source file
Utility/src/Overall.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Overall.cpp.i
.PHONY : Utility/src/Overall.cpp.i

Utility/src/Overall.s: Utility/src/Overall.cpp.s

.PHONY : Utility/src/Overall.s

# target to generate assembly for a file
Utility/src/Overall.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Overall.cpp.s
.PHONY : Utility/src/Overall.cpp.s

Utility/src/ShaderProgram.o: Utility/src/ShaderProgram.cpp.o

.PHONY : Utility/src/ShaderProgram.o

# target to build an object file
Utility/src/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/ShaderProgram.cpp.o
.PHONY : Utility/src/ShaderProgram.cpp.o

Utility/src/ShaderProgram.i: Utility/src/ShaderProgram.cpp.i

.PHONY : Utility/src/ShaderProgram.i

# target to preprocess a source file
Utility/src/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/ShaderProgram.cpp.i
.PHONY : Utility/src/ShaderProgram.cpp.i

Utility/src/ShaderProgram.s: Utility/src/ShaderProgram.cpp.s

.PHONY : Utility/src/ShaderProgram.s

# target to generate assembly for a file
Utility/src/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/ShaderProgram.cpp.s
.PHONY : Utility/src/ShaderProgram.cpp.s

Utility/src/Texture.o: Utility/src/Texture.cpp.o

.PHONY : Utility/src/Texture.o

# target to build an object file
Utility/src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Texture.cpp.o
.PHONY : Utility/src/Texture.cpp.o

Utility/src/Texture.i: Utility/src/Texture.cpp.i

.PHONY : Utility/src/Texture.i

# target to preprocess a source file
Utility/src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Texture.cpp.i
.PHONY : Utility/src/Texture.cpp.i

Utility/src/Texture.s: Utility/src/Texture.cpp.s

.PHONY : Utility/src/Texture.s

# target to generate assembly for a file
Utility/src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/Texture.cpp.s
.PHONY : Utility/src/Texture.cpp.s

Utility/src/mat4.o: Utility/src/mat4.cpp.o

.PHONY : Utility/src/mat4.o

# target to build an object file
Utility/src/mat4.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/mat4.cpp.o
.PHONY : Utility/src/mat4.cpp.o

Utility/src/mat4.i: Utility/src/mat4.cpp.i

.PHONY : Utility/src/mat4.i

# target to preprocess a source file
Utility/src/mat4.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/mat4.cpp.i
.PHONY : Utility/src/mat4.cpp.i

Utility/src/mat4.s: Utility/src/mat4.cpp.s

.PHONY : Utility/src/mat4.s

# target to generate assembly for a file
Utility/src/mat4.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/mat4.cpp.s
.PHONY : Utility/src/mat4.cpp.s

Utility/src/uvec3.o: Utility/src/uvec3.cpp.o

.PHONY : Utility/src/uvec3.o

# target to build an object file
Utility/src/uvec3.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/uvec3.cpp.o
.PHONY : Utility/src/uvec3.cpp.o

Utility/src/uvec3.i: Utility/src/uvec3.cpp.i

.PHONY : Utility/src/uvec3.i

# target to preprocess a source file
Utility/src/uvec3.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/uvec3.cpp.i
.PHONY : Utility/src/uvec3.cpp.i

Utility/src/uvec3.s: Utility/src/uvec3.cpp.s

.PHONY : Utility/src/uvec3.s

# target to generate assembly for a file
Utility/src/uvec3.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/uvec3.cpp.s
.PHONY : Utility/src/uvec3.cpp.s

Utility/src/vec2.o: Utility/src/vec2.cpp.o

.PHONY : Utility/src/vec2.o

# target to build an object file
Utility/src/vec2.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec2.cpp.o
.PHONY : Utility/src/vec2.cpp.o

Utility/src/vec2.i: Utility/src/vec2.cpp.i

.PHONY : Utility/src/vec2.i

# target to preprocess a source file
Utility/src/vec2.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec2.cpp.i
.PHONY : Utility/src/vec2.cpp.i

Utility/src/vec2.s: Utility/src/vec2.cpp.s

.PHONY : Utility/src/vec2.s

# target to generate assembly for a file
Utility/src/vec2.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec2.cpp.s
.PHONY : Utility/src/vec2.cpp.s

Utility/src/vec3.o: Utility/src/vec3.cpp.o

.PHONY : Utility/src/vec3.o

# target to build an object file
Utility/src/vec3.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec3.cpp.o
.PHONY : Utility/src/vec3.cpp.o

Utility/src/vec3.i: Utility/src/vec3.cpp.i

.PHONY : Utility/src/vec3.i

# target to preprocess a source file
Utility/src/vec3.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec3.cpp.i
.PHONY : Utility/src/vec3.cpp.i

Utility/src/vec3.s: Utility/src/vec3.cpp.s

.PHONY : Utility/src/vec3.s

# target to generate assembly for a file
Utility/src/vec3.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec3.cpp.s
.PHONY : Utility/src/vec3.cpp.s

Utility/src/vec4.o: Utility/src/vec4.cpp.o

.PHONY : Utility/src/vec4.o

# target to build an object file
Utility/src/vec4.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec4.cpp.o
.PHONY : Utility/src/vec4.cpp.o

Utility/src/vec4.i: Utility/src/vec4.cpp.i

.PHONY : Utility/src/vec4.i

# target to preprocess a source file
Utility/src/vec4.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec4.cpp.i
.PHONY : Utility/src/vec4.cpp.i

Utility/src/vec4.s: Utility/src/vec4.cpp.s

.PHONY : Utility/src/vec4.s

# target to generate assembly for a file
Utility/src/vec4.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/Utility/src/vec4.cpp.s
.PHONY : Utility/src/vec4.cpp.s

source/Funcs.o: source/Funcs.cpp.o

.PHONY : source/Funcs.o

# target to build an object file
source/Funcs.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Funcs.cpp.o
.PHONY : source/Funcs.cpp.o

source/Funcs.i: source/Funcs.cpp.i

.PHONY : source/Funcs.i

# target to preprocess a source file
source/Funcs.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Funcs.cpp.i
.PHONY : source/Funcs.cpp.i

source/Funcs.s: source/Funcs.cpp.s

.PHONY : source/Funcs.s

# target to generate assembly for a file
source/Funcs.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Funcs.cpp.s
.PHONY : source/Funcs.cpp.s

source/Globals.o: source/Globals.cpp.o

.PHONY : source/Globals.o

# target to build an object file
source/Globals.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Globals.cpp.o
.PHONY : source/Globals.cpp.o

source/Globals.i: source/Globals.cpp.i

.PHONY : source/Globals.i

# target to preprocess a source file
source/Globals.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Globals.cpp.i
.PHONY : source/Globals.cpp.i

source/Globals.s: source/Globals.cpp.s

.PHONY : source/Globals.s

# target to generate assembly for a file
source/Globals.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Globals.cpp.s
.PHONY : source/Globals.cpp.s

source/Graphics.o: source/Graphics.cpp.o

.PHONY : source/Graphics.o

# target to build an object file
source/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Graphics.cpp.o
.PHONY : source/Graphics.cpp.o

source/Graphics.i: source/Graphics.cpp.i

.PHONY : source/Graphics.i

# target to preprocess a source file
source/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Graphics.cpp.i
.PHONY : source/Graphics.cpp.i

source/Graphics.s: source/Graphics.cpp.s

.PHONY : source/Graphics.s

# target to generate assembly for a file
source/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Graphics.cpp.s
.PHONY : source/Graphics.cpp.s

source/Serializer.o: source/Serializer.cpp.o

.PHONY : source/Serializer.o

# target to build an object file
source/Serializer.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Serializer.cpp.o
.PHONY : source/Serializer.cpp.o

source/Serializer.i: source/Serializer.cpp.i

.PHONY : source/Serializer.i

# target to preprocess a source file
source/Serializer.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Serializer.cpp.i
.PHONY : source/Serializer.cpp.i

source/Serializer.s: source/Serializer.cpp.s

.PHONY : source/Serializer.s

# target to generate assembly for a file
source/Serializer.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/Serializer.cpp.s
.PHONY : source/Serializer.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_project.dir/build.make CMakeFiles/cmake_project.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... make"
	@echo "... cmake_project"
	@echo "... rebuild_cache"
	@echo "... SOIL"
	@echo "... SOIL/src/SOIL.o"
	@echo "... SOIL/src/SOIL.i"
	@echo "... SOIL/src/SOIL.s"
	@echo "... SOIL/src/image_DXT.o"
	@echo "... SOIL/src/image_DXT.i"
	@echo "... SOIL/src/image_DXT.s"
	@echo "... SOIL/src/image_helper.o"
	@echo "... SOIL/src/image_helper.i"
	@echo "... SOIL/src/image_helper.s"
	@echo "... SOIL/src/stb_image_aug.o"
	@echo "... SOIL/src/stb_image_aug.i"
	@echo "... SOIL/src/stb_image_aug.s"
	@echo "... Utility/src/Camera.o"
	@echo "... Utility/src/Camera.i"
	@echo "... Utility/src/Camera.s"
	@echo "... Utility/src/GL.o"
	@echo "... Utility/src/GL.i"
	@echo "... Utility/src/GL.s"
	@echo "... Utility/src/Overall.o"
	@echo "... Utility/src/Overall.i"
	@echo "... Utility/src/Overall.s"
	@echo "... Utility/src/ShaderProgram.o"
	@echo "... Utility/src/ShaderProgram.i"
	@echo "... Utility/src/ShaderProgram.s"
	@echo "... Utility/src/Texture.o"
	@echo "... Utility/src/Texture.i"
	@echo "... Utility/src/Texture.s"
	@echo "... Utility/src/mat4.o"
	@echo "... Utility/src/mat4.i"
	@echo "... Utility/src/mat4.s"
	@echo "... Utility/src/uvec3.o"
	@echo "... Utility/src/uvec3.i"
	@echo "... Utility/src/uvec3.s"
	@echo "... Utility/src/vec2.o"
	@echo "... Utility/src/vec2.i"
	@echo "... Utility/src/vec2.s"
	@echo "... Utility/src/vec3.o"
	@echo "... Utility/src/vec3.i"
	@echo "... Utility/src/vec3.s"
	@echo "... Utility/src/vec4.o"
	@echo "... Utility/src/vec4.i"
	@echo "... Utility/src/vec4.s"
	@echo "... source/Funcs.o"
	@echo "... source/Funcs.i"
	@echo "... source/Funcs.s"
	@echo "... source/Globals.o"
	@echo "... source/Globals.i"
	@echo "... source/Globals.s"
	@echo "... source/Graphics.o"
	@echo "... source/Graphics.i"
	@echo "... source/Graphics.s"
	@echo "... source/Serializer.o"
	@echo "... source/Serializer.i"
	@echo "... source/Serializer.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

